version: '3'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jupyterhub_data:/srv/jupyterhub
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyter/scipy-notebook:6d42503c684f
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
      - OAUTH_CALLBACK_URL
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
    restart: on-failure

  jupyterlab:
    image: jupyter/scipy-notebook:6d42503c684f
    container_name: jupyterlab-throaway
    command: echo

volumes:
  jupyterhub_data:
